### ISSUE TITLE
RG.PYEXECUTE not working

### ISSUE THREAD

**Issue by bwithai** [RedisGears/redisgears-py#45]
this exception is rise through this code
```
from gearsclient import GearsRemoteBuilder as GB
GB().run()
```

![issue](https://user-images.githubusercontent.com/76056239/210998332-cf2a883e-7f71-488f-b36e-558f1faecad2.png)

**Comment by chayim** [comment]
@bwithai I noticed that you haven't installed this library in the redisgears virtualenv as per the [README](https://github.com/RedisGears/redisgears-py#installing). This client is meant to be run within the Redis server context hosting gears.
