### ISSUE TITLE
Using hget in map function, return redundant values

### ISSUE THREAD

**Issue by gamblewin** [RedisGears/redisgears-py#49]
**code**
```python
from gearsclient import GearsRemoteBuilder as GB
from gearsclient import execute
import redis

conn = redis.Redis(host='127.0.0.1', port=6464, db=0)
conn.hset('student', 'name', 'osborn')

res = GB(reader='KeysOnlyReader', r=conn).\
    map(lambda x: execute('hget', 'student', 'name')).\
    run()

print(res)
```

**output**
<img width="532" alt="image" src="https://github.com/RedisGears/redisgears-py/assets/39117591/d52a4a8e-d31a-43a1-93b0-119a2240571f">

i expect to get one value which is 'osborn', but this code returns 5 'osborn', i don't know why this happen and how to fix it.

**Comment by MeirShpilraien** [comment]
`KeysOnlyReader` runs on each key in the database, I guess you have 5 keys so you run the `hget` command 5 times and got the result 5 times ...

**Comment by gamblewin** [comment]
@MeirShpilraien  Thx for replying.
I see, so if i only want to query hash student, i should put 'student' as parameter into run().
Still get two little questions, i see some examples which put a regex filter as parameter into run(), such as run('people*'),
1. but is that a fuzzy search for redis key? i remember that in real production environment, fuzzy search is not recommended due to poor performance.
2. if i put an exact string as parameter but not a regex filter, will the key search becomes faster?

**Comment by MeirShpilraien** [comment]
You should probably use the shardIDReader which will return a single record on each shard that can be mapped to anything you want (so you can simply read the key you want and it should not do any scanning).
https://oss.redis.com/redisgears/readers.html#shardsidreader

Please also notice that we now support JS with V8 (we will soon release our first RC release) with a fresh new API that you might find easier to use: https://github.com/RedisGears/RedisGears#readme
