### ISSUE TITLE
 Is Redis Gears execution atomic?

### ISSUE THREAD

**Issue by gamblewin** [RedisGears/redisgears-py#50]
If i have a python gears file for writing 1 million records into Redis.

Does the main thread of Redis block until the python file completes execution?

**Comment by MeirShpilraien** [comment]
Depends on how you are your code you can do it atomically and block Redis or not block Redis and lose the atomic.
Look at this link for more information: https://oss.redis.com/redisgears/runtime.html#atomic

**Comment by gamblewin** [comment]
@MeirShpilraien  Thx for replying, i've seen this part. Actually, i'm not familiar with python syntax. i'm not sure how to use the line `with atmoic()`, i thought it was built-in function of package gearsclient, but it's not.
