### ISSUE TITLE
redis gears transaction command

### ISSUE THREAD

**Issue by gamblewin** [RedisGears/redisgears-py#52]
I see the official document says that redis gears support transaction, so i give a try. Here's my code:

```python
def watch1(x):
    execute('watch', 'k1')
    execute('multi')
    v1 = execute('get', 'k1')
    if v1 is None:
        v1 = 0
    else:
        v1 = int(v1)
    execute('set', 'k1', v1 + 1)
    execute('exec')

GB(reader='ShardsIDReader', r=conn_gears). \
    map(watch1). \
    run()
```

this code reports mistake about `execute('exec')` this line, so i wonder what's the right command for transaction.

**Comment by MeirShpilraien** [comment]
Gears atomicity is not achived using a multi exec transaction, but instead you should use an atomic block: https://oss.redis.com/redisgears/runtime.html#atomic

**Comment by gamblewin** [comment]
> Gears atomicity is not achived using a multi exec transaction, but instead you should use an atomic block: https://oss.redis.com/redisgears/runtime.html#atomic

I see, but this would block the only working process of redis when running gears code, just like lua scipt. 
However, multi exec command would not block operation for those unwatched keys.

So using atomic block, during execution of gears function, other clients can not read from or write to redis?

Is there anyway that gears can only 'lock' specific keys and do not affect operations for other keys?

**Comment by MeirShpilraien** [comment]
> So using atomic block, during execution of gears function, other clients can not read from or write to redis?

Yes this is correct, gears does not provide anything more then lua with regards to atomicity.

> Is there anyway that gears can only 'lock' specific keys and do not affect operations for other keys?

No, currently it is not possible. Redis has a single GIL that protects all the keys.

**Comment by gamblewin** [comment]
> > So using atomic block, during execution of gears function, other clients can not read from or write to redis?
> 
> Yes this is correct, gears does not provide anything more then lua with regards to atomicity.
> 
> > Is there anyway that gears can only 'lock' specific keys and do not affect operations for other keys?
> 
> No, currently it is not possible. Redis has a single GIL that protects all the keys.

okay, get it, really appreciate for all the help you've offered.
